import type { ReportBlockDefinition } from '@/utils/assessments/assessment-report-template'

export function createReportBlockId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }

  return `v2_report_block_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`
}

export function createDemoReportBlocks(): ReportBlockDefinition[] {
  return [
    {
      id: createReportBlockId(),
      source: 'overall_classification',
      format: 'hero_card',
      content: { title: 'Your Overall Profile', eyebrow: 'Assessment Result' },
      enabled: true,
    },
    {
      id: createReportBlockId(),
      source: 'layer_profile',
      format: 'score_cards',
      content: { title: 'Core capability summary' },
      data: {
        layer: 'dimension',
        label_mode: 'external',
        body_source: 'summary_definition',
        show_band: true,
        show_low_high_meaning: true,
        behaviour_snapshot_mode: 'current_only',
        metric_key: 'display',
      },
      enabled: true,
    },
    {
      id: createReportBlockId(),
      source: 'trait_scores',
      format: 'score_cards',
      content: { title: 'Trait Breakdown' },
      filter: { max_items: 6 },
      enabled: true,
    },
    {
      id: createReportBlockId(),
      source: 'recommendations',
      format: 'bullet_list',
      content: { title: 'Development Recommendations' },
      enabled: true,
    },
    {
      id: createReportBlockId(),
      source: 'static_content',
      format: 'rich_text',
      content: {
        title: 'About This Report',
        body_markdown: 'This report was generated by the V2 assessment engine.',
      },
      enabled: true,
    },
  ]
}
