import type { V2ReportBlockDefinition } from '@/utils/assessments/v2-report-template'

export function createV2ReportBlockId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }

  return `v2_report_block_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`
}

export function createDemoV2ReportBlocks(): V2ReportBlockDefinition[] {
  return [
    {
      id: createV2ReportBlockId(),
      source: 'overall_classification',
      format: 'hero_card',
      content: { title: 'Your Overall Profile', eyebrow: 'Assessment Result' },
      enabled: true,
    },
    {
      id: createV2ReportBlockId(),
      source: 'dimension_scores',
      format: 'bar_chart',
      content: { title: 'Dimension Scores' },
      enabled: true,
    },
    {
      id: createV2ReportBlockId(),
      source: 'trait_scores',
      format: 'score_cards',
      content: { title: 'Trait Breakdown' },
      filter: { max_items: 6 },
      enabled: true,
    },
    {
      id: createV2ReportBlockId(),
      source: 'interpretations',
      format: 'insight_list',
      content: { title: 'Key Insights' },
      enabled: true,
    },
    {
      id: createV2ReportBlockId(),
      source: 'recommendations',
      format: 'bullet_list',
      content: { title: 'Development Recommendations' },
      enabled: true,
    },
    {
      id: createV2ReportBlockId(),
      source: 'static_content',
      format: 'rich_text',
      content: {
        title: 'About This Report',
        body_markdown: 'This report was generated by the V2 assessment engine.',
      },
      enabled: true,
    },
  ]
}
